backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  # - name: "events"
  #   label: "Events"
  #   folder: "src/pages/events"
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Description", name: "description", widget: "text"}
  #     - {label: "Link", name: "link", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/places/index.md"
        label: "Places"
        name: "places"
        widget: "list"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
      - file: "src/pages/events/index.md"
        label: "Events"
        name: "events"
        widget: "list"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "sring"}
          - {label: Image, name: image, widget: image}
